table Dim_Turma
	lineageTag: e910acda-ef6a-4a1b-b90f-3769536e5352

	column cod_turma
		dataType: int64
		formatString: 0
		lineageTag: 460973e9-bd79-4f37-9047-62c2e5076b17
		summarizeBy: none
		sourceColumn: cod_turma

		annotation SummarizationSetBy = Automatic

	column nome_turma
		dataType: string
		lineageTag: 44014264-9fe9-4b32-ad1e-a1c720bf519e
		summarizeBy: none
		sourceColumn: nome_turma

		annotation SummarizationSetBy = Automatic

	column modalidade_turma
		dataType: string
		lineageTag: 32e6596b-5bc7-42d7-b95b-2af10b3592ff
		summarizeBy: none
		sourceColumn: modalidade_turma

		annotation SummarizationSetBy = Automatic

	partition Dim_Turma = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\geova\OneDrive - UniCEUB\Área de Trabalho\amostra_evg.csv"),[Delimiter=",", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"cod_matricula", type text}, {"dt_matricula", type datetime}, {"nacionalidade", type text}, {"cod_turma", Int64.Type}, {"nome_turma", type text}, {"modalidade_turma", type text}, {"cod_curso", Int64.Type}, {"nome_curso", type text}, {"carga_horaria", Int64.Type}, {"dt_fim", type datetime}, {"sit_turma", type text}, {"instituicao", type text}, {"municipio_pessoa", type text}, {"uf_pessoa", type text}, {"conteudista", type text}, {"tematica", type text}, {"codigo_pessoa", type text}, {"sexo", type text}, {"idade", Int64.Type}, {"sit_matricula", type text}, {"poder", type text}, {"esfera", type text}, {"email_pessoa", type text}, {"telefone_pessoa", Int64.Type}, {"email_conteudista", type text}}),
				    #"Texto Extraído Antes do Delimitador" = Table.TransformColumns(#"Tipo Alterado", {{"dt_matricula", each Text.BeforeDelimiter(Text.From(_, "pt-BR"), " "), type text}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Texto Extraído Antes do Delimitador",{{"dt_matricula", type date}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Tipo Alterado1",{"cod_turma", "nome_turma", "modalidade_turma"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas", {"cod_turma"}),
				    #"Linhas Classificadas" = Table.Sort(#"Duplicatas Removidas",{{"cod_turma", Order.Ascending}}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Linhas Classificadas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Linhas em Branco Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

