table Dim_Pessoa
	lineageTag: 49621b04-e10f-484b-a31f-38fb76d9639a

	column codigo_pessoa
		dataType: string
		lineageTag: 87276812-15dd-43ec-b189-5b26bf2c0615
		summarizeBy: none
		sourceColumn: codigo_pessoa

		annotation SummarizationSetBy = Automatic

	column sexo
		dataType: string
		lineageTag: fbecdff1-9a7f-41dc-ace9-117f073b7e7b
		summarizeBy: none
		sourceColumn: sexo

		annotation SummarizationSetBy = Automatic

	column idade
		dataType: int64
		formatString: 0
		lineageTag: 89348341-4709-4b04-ac66-0fa361206231
		summarizeBy: none
		sourceColumn: idade

		annotation SummarizationSetBy = Automatic

	column email_pessoa
		dataType: string
		lineageTag: 3ebf4908-3bed-407b-a2f8-304f2104baed
		summarizeBy: none
		sourceColumn: email_pessoa

		annotation SummarizationSetBy = Automatic

	column telefone_pessoa
		dataType: int64
		formatString: 0
		lineageTag: 1bab256f-ff61-4554-b6f0-1a6bf8a05140
		summarizeBy: none
		sourceColumn: telefone_pessoa

		annotation SummarizationSetBy = Automatic

	column nacionalidade
		dataType: string
		lineageTag: 846ac8fc-3ebf-4807-8741-8476cee3bb95
		summarizeBy: none
		sourceColumn: nacionalidade

		annotation SummarizationSetBy = Automatic

	partition Dim_Pessoa = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\geova\OneDrive - UniCEUB\Área de Trabalho\amostra_evg.csv"),[Delimiter=",", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"cod_matricula", type text}, {"dt_matricula", type datetime}, {"nacionalidade", type text}, {"cod_turma", Int64.Type}, {"nome_turma", type text}, {"modalidade_turma", type text}, {"cod_curso", Int64.Type}, {"nome_curso", type text}, {"carga_horaria", Int64.Type}, {"dt_fim", type datetime}, {"sit_turma", type text}, {"instituicao", type text}, {"municipio_pessoa", type text}, {"uf_pessoa", type text}, {"conteudista", type text}, {"tematica", type text}, {"codigo_pessoa", type text}, {"sexo", type text}, {"idade", Int64.Type}, {"sit_matricula", type text}, {"poder", type text}, {"esfera", type text}, {"email_pessoa", type text}, {"telefone_pessoa", Int64.Type}, {"email_conteudista", type text}}),
				    #"Texto Extraído Antes do Delimitador" = Table.TransformColumns(#"Tipo Alterado", {{"dt_matricula", each Text.BeforeDelimiter(Text.From(_, "pt-BR"), " "), type text}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Texto Extraído Antes do Delimitador",{{"dt_matricula", type date}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Tipo Alterado1",{"codigo_pessoa", "sexo", "idade", "email_pessoa", "telefone_pessoa", "nacionalidade"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas", {"codigo_pessoa"}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Duplicatas Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Linhas Classificadas" = Table.Sort(#"Linhas em Branco Removidas",{{"idade", Order.Ascending}}),
				    #"Linhas em Branco Removidas1" = Table.SelectRows(#"Linhas Classificadas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Linhas em Branco Removidas1",1)
				in
				    #"Linhas Superiores Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

