table Dim_Poder
	lineageTag: 4b2f7937-809f-4460-8009-331799b7f917

	column cod_poder
		dataType: int64
		formatString: 0
		lineageTag: b2358b0b-d7d4-4767-b2e4-63352d5c8289
		summarizeBy: none
		sourceColumn: cod_poder

		annotation SummarizationSetBy = Automatic

	column poder
		dataType: string
		lineageTag: b9c1c8f2-77d1-4e3f-b552-57a96738455a
		summarizeBy: none
		sourceColumn: poder

		annotation SummarizationSetBy = Automatic

	partition Dim_Poder = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\geova\OneDrive - UniCEUB\Área de Trabalho\amostra_evg.csv"),[Delimiter=",", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"cod_matricula", type text}, {"dt_matricula", type datetime}, {"nacionalidade", type text}, {"cod_turma", Int64.Type}, {"nome_turma", type text}, {"modalidade_turma", type text}, {"cod_curso", Int64.Type}, {"nome_curso", type text}, {"carga_horaria", Int64.Type}, {"dt_fim", type datetime}, {"sit_turma", type text}, {"instituicao", type text}, {"municipio_pessoa", type text}, {"uf_pessoa", type text}, {"conteudista", type text}, {"tematica", type text}, {"codigo_pessoa", type text}, {"sexo", type text}, {"idade", Int64.Type}, {"sit_matricula", type text}, {"poder", type text}, {"esfera", type text}, {"email_pessoa", type text}, {"telefone_pessoa", Int64.Type}, {"email_conteudista", type text}}),
				    #"Texto Extraído Antes do Delimitador" = Table.TransformColumns(#"Tipo Alterado", {{"dt_matricula", each Text.BeforeDelimiter(Text.From(_, "pt-BR"), " "), type text}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Texto Extraído Antes do Delimitador",{{"dt_matricula", type date}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Tipo Alterado1",{"poder"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas"),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Duplicatas Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Linhas em Branco Removidas", "Índice", 333, 100, Int64.Type),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Índice Adicionado",{{"Índice", "cod_poder"}}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Renomeadas",{"cod_poder", "poder"})
				in
				    #"Colunas Reordenadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

