table Dim_Data
	lineageTag: 0c62de6a-5aa1-416b-91a5-cb8eb5ff79f7

	measure DT_Fim =
			
			CALCULATE(
			    COUNT(F_Matriculas[cod_matricula]),
			    USERELATIONSHIP(F_Matriculas[dt_fim], Dim_Data[Data])
			)
		formatString: 0
		lineageTag: be3a592e-d346-435e-8267-9f44d1f15d41

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: b7bed82f-20a5-4fe5-a4da-e286e6b825dc
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 71cd3339-5d85-4d28-bed7-cfff0bc418f5
			defaultHierarchy: LocalDateTable_48ce22f4-4886-40df-b570-237194f66554.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: ed26b801-b0c1-475f-a5ad-0a86e34de31e
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: e82dce06-af64-4e51-ab22-1717b375f088
		summarizeBy: none
		sourceColumn: Nome do Mês

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: 1f228d16-cd56-411b-848b-31de0dcd6532
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	partition Dim_Data = m
		mode: import
		source =
				let
				    Fonte = List.Min(F_Matriculas[dt_matricula]),
				    DtMin = List.Min(F_Matriculas[dt_matricula]),
				    DtMax = List.Max(F_Matriculas[dt_matricula]),
				    QntDias = Duration.Days(DtMax - DtMin)+1,
				    ConversaoTabela = List.Dates(DtMin, QntDias, #duration(1,0,0,0)),
				    #"Convertido para Tabela" = Table.FromList(ConversaoTabela, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Convertido para Tabela",{{"Column1", type date}}),
				    #"Coluna Duplicada" = Table.DuplicateColumn(#"Tipo Alterado", "Column1", "Column1 - Copiar"),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(Table.TransformColumnTypes(#"Coluna Duplicada", {{"Column1 - Copiar", type text}}, "pt-BR"), "Column1 - Copiar", Splitter.SplitTextByEachDelimiter({"/"}, QuoteStyle.Csv, false), {"Column1 - Copiar.1", "Column1 - Copiar.2"}),
				    #"Dividir Coluna por Delimitador1" = Table.SplitColumn(#"Dividir Coluna por Delimitador", "Column1 - Copiar.2", Splitter.SplitTextByEachDelimiter({"/"}, QuoteStyle.None, false), {"Column1 - Copiar.2.1", "Column1 - Copiar.2.2"}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Dividir Coluna por Delimitador1",{"Column1 - Copiar.1"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas",{{"Column1", "Data"}, {"Column1 - Copiar.2.1", "Mês"}, {"Column1 - Copiar.2.2", "Ano"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Ano", Int64.Type}}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Tipo Alterado1",{"Mês", "Ano"}),
				    #"Ano Inserido" = Table.AddColumn(#"Colunas Removidas1", "Ano", each Date.Year([Data]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Nome do Mês", each Date.MonthName([Data]), type text),
				    #"Trimestre Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Trimestre", each Date.QuarterOfYear([Data]), Int64.Type)
				in
				    #"Trimestre Inserido"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

